image:
  secretName: virtual-kubelet-aci-acr
  repository: mcr.microsoft.com
  name: oss/virtual-kubelet/virtual-kubelet
  tag: 1.6.1
  pullPolicy: Always

initImage:
  repository: mcr.microsoft.com
  name: oss/virtual-kubelet/init-validation
  initTag: 0.2.0
  pullPolicy: Always

namespace: vk-azure-aci

nodeName: "virtual-node-aci-linux-helm"
nodeOsType: "Linux"
monitoredNamespace: ""
apiserverCert:
apiserverKey:
logLevel:
disableVerifyClients: false
enableAuthenticationTokenWebhook: true

taint:
  enabled: true
  key: virtual-kubelet.io/provider
  value: "{{ .Values.provider }}"
  ## `effect` must be `NoSchedule`, `PreferNoSchedule` or `NoExecute`.
  effect: NoSchedule

trace:
  exporter: ""
  serviceName: "{{ .Values.nodeName }}"
  sampleRate: 0

providers:
  azure:
    enableRealTimeMetrics: true
    ## Set to true if deploying to Azure Kubernetes Service (AKS), otherwise false
    targetAKS: true
    clientId:
    clientKey:
    tenantId:
    subscriptionId:
    managedIdentityID:
    ## `aciResourceGroup` and `aciRegion` are required only for non-AKS deployments
    aciResourceGroup:
    aciRegion:
    masterUri:
    loganalytics:
      enabled: false
      workspaceId:
      workspaceKey:
      clusterResourceId:
    vnet:
      enabled: false
      vnetResourceGroup:
      vnetName:
      subnetName: virtual-node-aci
      ## If subnet already created on vnet, don't pass subnetCidr if it doesn't match the existing one.
      ## If cluster subnet has a different range, please specify its value in clusterCidr
      subnetCidr: 10.241.0.0/16
      # clusterCidr defaults to 10.240.0.0/16 if not specified
      clusterCidr:
      # kubeDnsIp defaults to 10.0.0.10 if not specified
      kubeDnsIp: 10.0.0.10

provider: azure

## Install Default RBAC roles and bindings
rbac:
  install: true
  serviceAccountName: virtual-kubelet-helm
  ## RBAC api version
  apiVersion: v1
  ## Cluster role reference
  roleRef: cluster-admin
