{{ if .Values.rbac.install }}
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: ClusterRoleBinding
metadata:
  name: {{ template "vk.fullname" . }}-{{ .Values.rbac.serviceAccountName }}
{{ include "vk.labels" . | indent 2 }}
subjects:
- kind: ServiceAccount
  name: {{ template "vk.fullname" . }}-{{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.roleRef }}
{{ end }}
