run:
  timeout: 10m

linters-settings:
  gci:
    skip-generated: true

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - typecheck
    - unused
  # Run with --fast=false for more extensive checks
  fast: true
