name: publish_helm_chart

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/chart.yaml"
      - "charts/**"
  create:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          target_dir: charts
          linting: off
