name: lint

concurrency:
  group:  ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - release-**
    paths-ignore: ['docs/**', '**.md', '**.mdx', '**.png', '**.jpg']

env:
  # Common versions
  GO_VERSION: '1.20'

jobs:
  lint:
    name: "Lint & Format"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Format
        run: make fmt

      - name: golangci-lint
        run: make lint
